### ISSUE TITLE
Improve OO structure and documentation

### ISSUE THREAD

**Issue by RubenVerborgh** [pabloem/Server.js#2]
The functionality of some classes does not seem to match their name.

The functionality of some classes does not seem to match their name.
- `ChangeSet` appears to model a change set, while its main/only responsibility actually seems downloading and parsing that dataset. It would seem more logical that a change set manager (or change set downloader) object creates changesets. If changesets themselves only need to be represented by the triples they contain (as seems to be the case), then perhaps a class for `ChangeSet` is not needed.
  - In JavaScript, don't write things like `x.getTriples`; just directly expose `x.triples`.
- `ChangesetCounter` is a good example (name matches functionality). The documentation is a bit off though: instead of `Method: ChangesetCounter`, say `A ChangesetCounter represents…`. Then you can explain how the constructor can be called.
- In `ChangesetManager`, don't monkey patch the `this._afterListDownload` etc. methods. Instead, directly use `this.downloadChangesets`, and patch these in unit tests as needed.
- Ensure that a `PollingAgent` can be started and stopped. ([The constructor should never start a complex job](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/).)

In all classes, write a short statement about what the object does ([example](https://github.com/LinkedDataFragments/Server.js/blob/v1.1.5/lib/datasources/IndexDatasource.js#L3)). This makes it easier to see what an object does, and to verify whether it needs to be an object indeed.

**Comment by pabloem** [comment]
I started working on these.
Regarding the `Changeset` class: I created a class of its own, to encapsulate the functionality of decompressing and parsing a changeset, so that if the changeset format changes in any way, only the `Changeset` class itself will require changes. Also, I felt like this functionality escapes the scope of the `ChangesetManager` class. It stores not only the triples, but also the operation to apply with this triples (removal, or addition); as well as URL. Do you feel this doesn't warrant its own class?
We could also add a `ChangesetDownloader` class that keeps this functionality, and the changesets are simple dictionaries.
What do you think, Ruben?

**Comment by RubenVerborgh** [comment]
I'd go for `ChangesetDownloader`, because this best reflects its functionality.

**Comment by pabloem** [comment]
Okay, sounds reasonable. I'll work to add that. The changesets will now just be dictionaries then.

**Comment by pabloem** [comment]
Added `ChangesetDownloader` and removed `Changeset` classes. Their code is almost exactly the same.

**Comment by RubenVerborgh** [comment]
Great, thanks. It's not that I want to be a purist, but giving things the right name makes it easier to go back on the code afterwards.

**Comment by pabloem** [comment]
I understand and agree :)
